[package]
name = "lib-pxc"
version = "0.1.0"
edition = "2021"

[dependencies]
env_logger = "0.11.5"
log = "0.4.22"
thiserror = "1.0.66"
bincode = "1.3"                                    # For binary serialization
serde = { version = "1.0", features = ["derive"] } # Serialization
